export const ERROR_CODES = {
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_REVOKED_TOKEN: "AUTH_REVOKED_TOKEN",
  ACL_DENIED: "ACL_DENIED",
  CONN_QUOTA_EXCEEDED: "CONN_QUOTA_EXCEEDED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  BACKPRESSURE_OVERFLOW: "BACKPRESSURE_OVERFLOW",
  PROTO_REGISTRATION_CONFLICT: "PROTO_REGISTRATION_CONFLICT",
  PROTO_UNKNOWN_ACTION: "PROTO_UNKNOWN_ACTION",
  PROTO_INVALID_PAYLOAD: "PROTO_INVALID_PAYLOAD",
  ROUTE_NO_RECIPIENT: "ROUTE_NO_RECIPIENT",
  ROUTE_PEER_OFFLINE: "ROUTE_PEER_OFFLINE",
  ROUTE_DELIVERY_TIMEOUT: "ROUTE_DELIVERY_TIMEOUT",
  GATEWAY_UPSTREAM_TIMEOUT: "GATEWAY_UPSTREAM_TIMEOUT",
  GATEWAY_UPSTREAM_UNAVAILABLE: "GATEWAY_UPSTREAM_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ROUTE_FAILURE_STAGES = {
  RESOLVE: "resolve",
  AUTH: "auth",
  EGRESS: "egress"
} as const;

export type RouteFailureStage =
  (typeof ROUTE_FAILURE_STAGES)[keyof typeof ROUTE_FAILURE_STAGES];
