export const ERROR_CODES = {
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_REVOKED_TOKEN: "AUTH_REVOKED_TOKEN",
  ACL_DENIED: "ACL_DENIED",
  CONN_QUOTA_EXCEEDED: "CONN_QUOTA_EXCEEDED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  BACKPRESSURE_OVERFLOW: "BACKPRESSURE_OVERFLOW",
  PROTO_REGISTRATION_CONFLICT: "PROTO_REGISTRATION_CONFLICT",
  PROTO_UNKNOWN_ACTION: "PROTO_UNKNOWN_ACTION",
  PROTO_INVALID_PAYLOAD: "PROTO_INVALID_PAYLOAD",
  ROUTE_NO_RECIPIENT: "ROUTE_NO_RECIPIENT",
  ROUTE_PEER_OFFLINE: "ROUTE_PEER_OFFLINE",
  ROUTE_DELIVERY_TIMEOUT: "ROUTE_DELIVERY_TIMEOUT",
  SERVER_DRAINING: "SERVER_DRAINING",
  GATEWAY_UPSTREAM_TIMEOUT: "GATEWAY_UPSTREAM_TIMEOUT",
  GATEWAY_UPSTREAM_UNAVAILABLE: "GATEWAY_UPSTREAM_UNAVAILABLE",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const CLIENT_ERROR_CODES = {
  CLIENT_NOT_READY: "CLIENT_NOT_READY",
  CLIENT_TRANSPORT_CLOSED: "CLIENT_TRANSPORT_CLOSED",
  CLIENT_DELIVERY_TIMEOUT: "CLIENT_DELIVERY_TIMEOUT",
  CLIENT_PROTOCOL_ERROR: "CLIENT_PROTOCOL_ERROR"
} as const;

export type ClientErrorCode = (typeof CLIENT_ERROR_CODES)[keyof typeof CLIENT_ERROR_CODES];
export type SdkErrorCode = ErrorCode | ClientErrorCode;
